source 'https://rubygems.org'

gem 'rake'
gem 'asciidoctor'

gem 'json'
gem 'awesome_print'

gem 'asciidoctor-pdf'

gem 'coderay'
gem 'pygments.rb'
gem 'thread_safe'

gem 'asciidoctor-mathematical'
